from os import environ

env = Environment(tools=['default', 'quex'],
                  ENV=environ,
                  CPPPATH=[environ['QUEX_PATH']],
                  CPPDEFINES=['QUEX_OPTION_ASSERTS_WARNING_MESSAGE_DISABLED'])

lexer_src = env.Quex(source='hello',
                     QUEXLANG='C++',
                     QUEXOUTDIR=Dir('quex').abspath,
                     QUEXENGINE='scanner',
                     QUEXENGINENS='my::')

program = env.Program(target='test',
                      source=[env.Glob('*.cpp'),
                              env.Glob('quex/*.cpp')])

env.Depends(target=program, dependency=lexer_src)

# vim:ft=python
